// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxruijxpfxupymcmjbne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cnVpanhwZnh1cHltY21qYm5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODA1OTAsImV4cCI6MjA3NDM1NjU5MH0.fvd-W4knHqSzWYwoIYxnLc84FkesjDCuXNDne4tJABw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});